### ISSUE TITLE
[BUG] pyflyte fails with import error with python version 3.9.10

### ISSUE THREAD

**Issue by AlekhyaSasi** [flyteorg/flyte#2261]
### Describe the bug

When packaging the workflow, with Python version 3.9.10 & protobuf version 3.19.4, `pyflyte` fails with

`ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/opt/homebrew/lib/python3.9/site-packages/google/protobuf/pyext/__init__.py)`

This seems to work with Python version 3.9.7.

### Expected behavior

pyflyte should succeed packaging.

### Additional context to reproduce

After completing the `build` part of getting-started: https://docs.flyte.org/en/latest/getting_started/build.html

1. `brew install flyteorg/homebrew-tap/flytectl`
1. `flytectl sandbox start --source .`
1. `flytectl sandbox exec -- docker build . --tag "myapp:v1"`
1. `pyflyte --pkgs flyte.workflows package --image "myapp:v1"`

### Screenshots

![image](https://user-images.githubusercontent.com/21109744/158547823-734e90d4-26ec-48a2-b5ae-a13e48bcbbba.png)

![image](https://user-images.githubusercontent.com/21109744/158547869-5836aa81-37cd-4639-8ba3-4d6d8522cb02.png)

![image](https://user-images.githubusercontent.com/21109744/158547907-357a1207-754b-42ee-9898-3d39eb7a13af.png)

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by eapolinario** [comment]
@AlekhyaSasi , can you confirm that you ran this on an M1 mac?

I tested this on linux using that exact version and couldn't repro:
```
❯ pip freeze | grep -E "(protobuf|flyte)"
flyteidl==0.23.1
flytekit==0.31.0
protobuf==3.19.4
❯ uname -a
Linux pop-os 5.16.11-76051611-generic #202202230823~1646248261~21.10~2b22243 SMP PREEMPT Wed Mar 2 20: x86_64 x86_64 x86_64 GNU/Linux
❯ python
Python 3.9.10 (main, Mar 16 2022, 08:50:41)
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf.pyext import _message
```

**Comment by AlekhyaSasi** [comment]
@eapolinario, yes its an M1mac.

**Comment by eapolinario** [comment]
I confirmed that this is an issue on M1. This is being tracked on the protobuf side in https://github.com/protocolbuffers/protobuf/issues/8820.

**Comment by eapolinario** [comment]
The workaround described in https://github.com/protocolbuffers/protobuf/issues/8820#issuecomment-961552604 unblocked this. Next step is to figure out how/if we can incorporate this in our install scripts.
