### ISSUE TITLE
Add support Pandera 0.20+ in flytekitplugins-pandera

### ISSUE THREAD

**Issue by pingsutw** [flyteorg/flyte#5531]
### Motivation: Why do you think this is important?

In this [PR](https://github.com/flyteorg/flytekit/pull/2539), we set the upper bound for Pandera due to test failure

```
FAILED tests/test_plugin.py::test_pandera_dataframe_type_hints - AttributeError: module 'pandera' has no attribute 'SchemaModel'
```

### Goal: What should the final outcome look like, ideally?

the plugin should work with Pandera 0.20+

### Describe alternatives you've considered 

NA

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes
