### ISSUE TITLE
[BUG] 1.3.0 broke task execution

### ISSUE THREAD

**Issue by honnix** [flyteorg/flyte#3261]
### Describe the bug

After upgraded to 1.3.0, `remote.execute` stopped working with exception:

```python
...
                # We need to manually make a map of the nodes since there is none for single task executions
                # Assume the first one is the only one.
                node_mapping = (
                    {
>                       task_node_exec[0].id.node_id: FlyteNode(
                            id=flyte_entity.id,
                            upstream_nodes=[],
                            bindings=[],
                            metadata=NodeMetadata(name=""),
                            flyte_task=flyte_entity,
                        )
                    }
                    if len(task_node_exec) >= 1
                    else {}  # This is for the case where node executions haven't appeared yet
                )
E               TypeError: __init__() got an unexpected keyword argument 'flyte_task'
.tox/py38-test/lib/python3.8/site-packages/flytekit/remote/remote.py:1454: TypeError
```

As commented in https://github.com/flyteorg/flytekit/pull/1348#issuecomment-1402255450, it seems to be that PR breaking it during refactoring.

### Expected behavior

`remote.execute` should work

### Additional context to reproduce

* Upgrade to 1.3.0
* Do the following
``` python
execution = remote.execute(
        ...
    )
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by kumare3** [comment]
this sounds, odd, `pyflyte run` uses this same code path. Checking!

**Comment by kumare3** [comment]
ohh i see it, its in sync execution. so the wait is broken?

**Comment by wild-endeavor** [comment]
https://github.com/flyteorg/flytekit/pull/1422
