### ISSUE TITLE
[BUG] Optional list arg is causing UI launch form to white screen

### ISSUE THREAD

**Issue by lauralindy** [flyteorg/flyte#4033]
### Describe the bug

After upgrading to 1.9.0 or 1.9.1, when I click on the launch form or relaunch form for workflows that have optional list args, the page will just flash the form and then go white screen.

Non-optional lists don't do this. 

### Expected behavior

Form should open up and allow input.

### Additional context to reproduce

```
from flytekit import task, workflow
import typing

@task
def some_task(a: typing.Optional[typing.List[int]]):
    print(a)

@workflow
def my_wf(x: typing.Optional[typing.List[int]]):
    some_task(a=x)
```

### Screenshots

console logs
```
react-dom.production.min.js:125 Error: empty string
    at Function.d [as fromString] (vendor.d3268180b8c0d189c23e.js:2:21291)
    at Object.toLiteral (main.7d9178e441dc822c8094.js:1:299325)
    at Object.typeDefinitionToDefaultValue (main.7d9178e441dc822c8094.js:1:294199)
    at main.7d9178e441dc822c8094.js:1:266673
    at Array.reduce (<anonymous>)
    at main.7d9178e441dc822c8094.js:1:266522
    at t.UnionInput (main.7d9178e441dc822c8094.js:1:266721)
    at we (react-dom.production.min.js:84:293)
    at zj (react-dom.production.min.js:226:496)
    at Th (react-dom.production.min.js:152:223)
Me @ react-dom.production.min.js:125
main.7d9178e441dc822c8094.js:1 Error: empty string
    at Function.d [as fromString] (vendor.d3268180b8c0d189c23e.js:2:21291)
    at Object.toLiteral (main.7d9178e441dc822c8094.js:1:299325)
    at Object.typeDefinitionToDefaultValue (main.7d9178e441dc822c8094.js:1:294199)
    at main.7d9178e441dc822c8094.js:1:266673
    at Array.reduce (<anonymous>)
    at main.7d9178e441dc822c8094.js:1:266522
    at t.UnionInput (main.7d9178e441dc822c8094.js:1:266721)
    at we (react-dom.production.min.js:84:293)
    at zj (react-dom.production.min.js:226:496)
    at Th (react-dom.production.min.js:152:223)
```

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

**Comment by ashrielbrian** [comment]
Seeing this issue as well on 1.9.1

**Comment by gilad2905** [comment]
Still happens in 1.10.2
![image](https://github.com/flyteorg/flyte/assets/6312585/80656fda-bfc5-41a9-adf8-580e15117c42)
![image](https://github.com/flyteorg/flyte/assets/6312585/b68e2916-65d7-4322-b3c5-f5e6661a6b3e)
